openapi: 3.0.0
info:
  title: Test
  version: 1.0.1
# Since OAS 3.1.0 the paths element isn't necessary. Now a valid OpenAPI Document can describe only paths, webhooks, or even only reusable components
webhooks:
  # Each webhook needs a name
  newPet:
    # This is a Path Item Object, the only difference is that the request is initiated by the API provider
    post:
      requestBody:
        description: Information about a new pet in the system
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        "200":
          description: Return a 200 status to indicate that the data was received successfully

components:
  schemas:
    Pet:
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          oneOf:
            - type: string
            - type: integer
        age:
          type: integer
          format: int64
        added:
          type: string

