openapi: "3.0.0"
info:
  version: 1.0.1
  title: Test Proto
components:
  schemas:
    Pet:
      type: object
      required:
        - name
        - id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
