openapi: "3.0.0"
info:
  version: 1.0.1
  title: Test Proto
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - age
        - name
      properties:
        id:
          type: float
        name:
          type: string
        age:
          type: int
