# The configuration schema is defined by the service.proto file.
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto

type: google.api.Service
config_version: 3
name: flame-4lynqeotzq-uw.a.run.app
title: Full Lifecycle API Management
apis:
  - name: google.cloud.apigee.flame.v1alpha1.Flame
backend:
  rules:
    - selector: "*"
      address: grpcs://flame-backend-4lynqeotzq-uw.a.run.app
usage:
  rules:
    - selector: "*"
      allow_unregistered_calls: true
