# The configuration schema is defined by the service.proto file.
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto

type: google.api.Service
config_version: 3
name: flame-yr4odda7na-uw.a.run.app
title: Full Lifecycle API Management
apis:
  - name: google.cloud.apigee.flame.v1alpha1.Flame
backend:
  rules:
    - selector: "*"
      address: grpcs://flame-backend-yr4odda7na-uw.a.run.app
authentication:
  providers:
  - id: google_service_account
    issuer: flamedemo@flamedemo.iam.gserviceaccount.com
    jwks_uri: https://www.googleapis.com/robot/v1/metadata/x509/flamedemo@flamedemo.iam.gserviceaccount.com
  rules:
  - selector: "*"
    requirements:
      - provider_id: google_service_account